# FilePath: server/hub/config/config.yaml
server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: "15s"
  write_timeout: "15s"
  shutdown_timeout: "30s"

database:
  timescaledb:
    host: "localhost"
    port: 5432
    user: "w4b"
    dbname: "w4b_sensors"
    sslmode: "disable"

  postgres_app:
    host: "localhost"
    port: 5432
    user: "w4b"
    dbname: "w4b_app"
    sslmode: "disable"

redis:
  host: "localhost"
  port: 6379
  db: 0

keycloak:
  url: "http://localhost:30080"
  realm: "w4b"
  client_id: "w4b-api"

monitoring:
  prometheus_port: 9090
  log_level: "info"

filestore:
  base_path: "/data/w4b/files"
  max_file_size: 10485760  # 10MB in bytes
