# /server/w4b_containers/config/vector/vector.yaml

data_dir: "/vector"

sources:
  docker_logs:
    type: "docker_logs"
    include_containers: ["hive_*"]

  host_metrics:
    type: "host_metrics"
    filesystem:
      devices:
        excludes: ["/dev/loop*"]

  internal_metrics:
    type: "internal_metrics"

transforms:
  docker_parse:
    type: "remap"
    inputs: ["docker_logs"]
    source: |
      . = parse_json!(.message) ?? .message
      .timestamp = parse_timestamp!(.timestamp, format: "%+")
      .container_name = split!(.container_name, "_")[1] ?? .container_name

  metrics_parse:
    type: "remap"
    inputs: ["host_metrics", "internal_metrics"]
    source: |
      .service = "vector"
      .environment = "production"

sinks:
  loki:
    type: "loki"
    inputs: ["docker_parse"]
    endpoint: "http://loki:3100"
    encoding:
      codec: "json"
    labels:
      container: "{{ container_name }}"
      service: "{{ service_name }}"
      level: "{{ level }}"

  prometheus:
    type: "prometheus_exporter"
    inputs: ["metrics_parse"]
    endpoint: "0.0.0.0:9598"

  console:
    type: "console"
    inputs: ["docker_parse"]
    encoding:
      codec: "json"
    target: "stdout"