-- /server/w4b_containers/scripts/init-keycloak-db.sql

CREATE DATABASE keycloak WITH ENCODING 'UTF8';
\c keycloak

CREATE USER ${W4B__POSTGRES_KEYCLOAK_USER} WITH PASSWORD '${W4B__POSTGRES_KEYCLOAK_PASSWORD}';
ALTER DATABASE keycloak OWNER TO ${W4B__POSTGRES_KEYCLOAK_USER};
GRANT ALL PRIVILEGES ON DATABASE keycloak TO ${W4B__POSTGRES_KEYCLOAK_USER};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${W4B__POSTGRES_KEYCLOAK_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${W4B__POSTGRES_KEYCLOAK_USER};

ALTER USER ${W4B__POSTGRES_KEYCLOAK_USER} WITH SUPERUSER;