# /server/w4b_containers/config/prometheus/prometheus.yml

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'hive-monitor'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'spokes'
    scrape_interval: 30s
    metrics_path: '/metrics'
    tls_config:
      insecure_skip_verify: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
    file_sd_configs:
      - files:
          - '/etc/prometheus/spoke_targets.yml'
        refresh_interval: 5m

  - job_name: 'api'
    static_configs:
      - targets: ['api:8080']

  - job_name: 'keycloak'
    static_configs:
      - targets: ['keycloak:8443']
    metrics_path: '/metrics'
    scheme: 'https'
    tls_config:
      insecure_skip_verify: true

  - job_name: 'databases'
    static_configs:
      - targets:
        - 'timescaledb:5432'
        - 'postgres_app:5432'
        - 'postgres_keycloak:5432'
    metrics_path: '/metrics'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'

