FROM postgres:17.2

# Set environment variables for database, user, and password
ENV POSTGRES_DB testdb
ENV POSTGRES_USER testuser
ENV POSTGRES_PASSWORD testpassword

# Expose the default PostgreSQL port
EXPOSE 5432